---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-provider-app
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: my-provider-service
  template:
    metadata:
      name: my-provider-app
      labels:
        service: my-provider-service
        name: my-provider-app
    spec:
      containers:
        - name: my-provider-app
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          imagePullPolicy: Always
          image: lalit2109/demo:latest
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 0.4
              memory: 64Mi
            requests:
              cpu: 0.2
              memory: 64Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
